- Systematic:
    SampleNames:
    - ND_*
    - FD_*
    - ATM
    Error: 1.0
    FlatPrior: false
    Names:
      FancyName: MaCCQE
      ParameterName: MaCCQE
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterValues:
      Generated: 0.0
      PreFitValue: 0.0
    SplineInformation:
      Mode:
      - 0
      SplineName: MaCCQE
      Type: PerEvent
    StepScale:
      MCMC: 0.4
    Type: Spline
    ParameterGroup: Xsec
- Systematic:
    SampleNames:
    - ND_*
    - FD_*
    - ATM
    Error: 1.0
    FlatPrior: false
    Names:
      FancyName: MaRES
      ParameterName: MaRES
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterValues:
      Generated: 0.0
      PreFitValue: 0.0
    SplineInformation:
      Mode:
      - 0
      SplineName: MaRES
      Type: PerEvent
    StepScale:
      MCMC: 0.4
    Type: Spline
    ParameterGroup: Xsec
- Systematic:
    SampleNames:
    - ND_*
    - FD_*
    - ATM
    Error: 1.0
    FlatPrior: false
    Names:
      FancyName: MEC_C
      ParameterName: MEC_C
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterValues:
      Generated: 1.0
      PreFitValue: 1.0
    SplineInformation:
      Mode:
      - 0
      SplineName: MEC_C
      Type: PerEvent
    StepScale:
      MCMC: 0.4
    Type: Spline
    ParameterGroup: Xsec
- Systematic:
    SampleNames:
    - ND_*
    - FD_*
    - ATM
    Error: 1.0
    FlatPrior: false
    Names:
      FancyName: FSI_pi_abs
      ParameterName: FSI_pi_abs
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterValues:
      Generated: 0.0
      PreFitValue: 0.0
    SplineInformation:
      Mode:
      - 0
      SplineName: FSI_pi_abs
      Type: PerEvent
    StepScale:
      MCMC: 0.4
    Type: Spline
    ParameterGroup: Xsec
